version: "2.6"

services:

  socksproxy:
    build:
      context: ../..
      dockerfile: docker/tlssocksproxy/Dockerfile
    restart: unless-stopped
    command:
      - "-addr=0.0.0.0:8000"
      - "-server=tunneltunnel:8000"
      - "-insecure-skip-verify"
    ports:
      - 8000:8000
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"   

  tunneltunnel:
    build:
      context: ../..
      dockerfile: docker/tcpproxy/Dockerfile
    restart: unless-stopped
    command:
      - "-addr=0.0.0.0:8000"
      - "-destination=tunnel:8000"
    expose:
      - 8000
    networks:
      - default
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"   

  tunnel:
    build:
      context: ../..
      dockerfile: docker/tcpproxy/Dockerfile
    restart: unless-stopped
    command:
      - "-addr=0.0.0.0:8000"
      - "-destination=tlssocks:8001"
    expose:
      - 8000
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  tlssocks:
    build:
      context: ../..
      dockerfile: docker/tlssocks/Dockerfile
    restart: unless-stopped
    command:
      - "-addr=0.0.0.0:8001"
      - "-auth=/tlssocks/users.htpasswd"
      - "-destinations=/tlssocks/destinations.yaml"
      - "-cert=/tlssocks/certificate.crt"
      - "-key=/tlssocks/certificate.key"
    expose:
      - 8001
    volumes:
      - ./tlssocks:/tlssocks
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"      
